##In GitHub Actions there's not an action called Merge Request, this kind of action is from GitLab, however, in GitHub
##we have pull-request, which actually makes the same thing, the difference is purely the begining of the action.
#name: pull-request

#on:
#  pull_request:
#    branches:
#      - main
#    types:
#      - closed

# Later, in the jobs section of your actions.yml file.
#jobs:
#  if_merged:
#    if: github.event.pull_request.merged == true
#    runs-on: ubuntu-latest
#    steps:
#    - run: |
#        echo The PR was successfully merged.
