name: pipeline

on: [push]

jobs:
  analysis:
    name: Fortify Static Application Security Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
    
  merge:
    name: Merge Phase
    needs: [analysis]
    runs-on: ubuntu-latest
    #if:
      #This "if" will be the validator about security before the branch would be merge
      #github.event.pull_request.merged == true
      
    ##This section will made the auto merge
    steps:
      - name: automerge
        uses: "mtanzi/action-automerge@v1"
        id: automerge
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          source: 'untested'
          target: 'main'
